### ISSUE TITLE
Is there an agent file for your extension that will be used by the check_mk agent?

### ISSUE THREAD

**Issue by greavette** [zito/cmk-ups#1]
Hello,

I realize that it's been 4 years since you've written this cmk for check_mk but I'm hoping you would be so kind as to answer a question for me regarding this cmk file you've created.

I've installed snmp on my remote (debian) host and I've added this host to check_mk.  I've installed your cmk-ups extension. 

I'm very new to check_mk so other extensions I've used had an agent script that I would put in /usr/lib/check_mk_agent/plugins/ folder on my host so that the check_mk agent can gather the necessary information from my USB attached UPS device.  I'm not seeing an agent script with your extension.  Could you be so kind as to explain to me what I need to do to ensure your extension grabs the necessary UPS details from my monitored host.

Thank you.

**Comment by zito** [comment]
Hello,

On Wed, Oct 28, 2015 at 01:17:18PM -0700, greavette wrote:

> ...
> I've installed snmp on my remote (debian) host and I've added this
> host to check_mk.  I've installed your cmk-ups extension. 

The check is for UPS HW with SNMP agent (with network interface).

## Regards

Zito

**Comment by greavette** [comment]
Thanks very much Zito for the reply.  Much appreciated!
